"""Add PII Type enum to column

Revision ID: d2c711b84996
Revises: d1daff1715f7
Create Date: 2021-08-15 19:51:09.656527

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision = "d2c711b84996"
down_revision = "d1daff1715f7"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("columns", sa.Column("pii_type", sa.String, nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("columns", "pii_type")
    # ### end Alembic commands ###
